#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use App\Command\SolvePartOneCommand;
use App\Command\SolvePartTwoCommand;
use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new SolvePartOneCommand());
$application->add(new SolvePartTwoCommand());

$application->run();